db:
    image: mongo
    volumes:
        - /root/www/db:/data
    container_name: db
    restart: always

www:
    build: .
    ports:
        - "80:8080"
    volumes:
        - /root/www/logs:/www/logs
        - /root/www/public:/www/public
    links:
        - db
    container_name: www
    restart: always
